trigger: none
pool:
  vmImage: 'ubuntu-latest'

variables:
  jmxFile: 'test.jmx'

stages:
  - stage: JMeter
    displayName: Run JMeter from binary
    jobs:
      - job: Jmeter
        displayName: Test
        steps:
          - pwsh: | #bash or powershell - both can run on ubuntu
              function Start-CommandInsideDocker($ContainerName, $Command){
                docker exec $ContainerName sh -c "${Command}"
              }
              $ContainerName='jmeter'
              $BaseDir=${pwd}
              Write-Host "Mounting $BaseDir/201_azure"

              #Running Jmeter container in detached mode with volumes mounted
              docker run -d `
              --name ${ContainerName} `
              --entrypoint tail `
              --volume ${BaseDir}/201_azure/:/jmx/ gabrielstar/crux-master:0.0.1 `
               -f /dev/null

              #Showing container started
              Write-Host "Started container ${ContainerName} "
              docker ps -a --no-trunc --filter name=^/${ContainerName}$

              #command is executed inside ubuntu-like container
              Start-CommandInsideDocker "$ContainerName" "ls /jmx"
              Start-CommandInsideDocker "$ContainerName" "sh /jmeter/apache-jmeter-*/bin/jmeter.sh -n -t /jmx/$(jmxFile)"
              docker stop "$ContainerName"
            displayName: Run Test

          - task: PublishPipelineArtifact@1
            displayName: Archive JMeter Artifacts
            inputs:
              path: jmeter_artifacts
              artifact: JmeterFiles

          - task: PublishPipelineArtifact@1
            displayName: Archive JMeter HTML Report
            inputs:
              path: html
              artifact: JmeterReport