trigger: none
pool:
  name: Default
  demands:
    - agent.os -equals Linux
stages:
  - stage: MyStage
    displayName: My Stage
    jobs:
      - job: MyJob
        displayName: My Job
        steps:
          - bash: |
              echo "something"
            displayName: Display Something in bash

          - pwsh: |
              Write-Host "something"
            displayName: Display Something in pwsh