trigger: none
pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: JMeterParameters
  type: string
  default: "-Jthreads=1"

- name: JMXFile
  type: string
  default: "test.jmx"

variables:
  containerName: jmeter
  containerImage: gabrielstar/crux-master:0.0.1
  repoDir: $(System.DefaultWorkingDirectory)/201_azure/
  containerDir: /jmx/

stages:
  - stage: JMeter
    displayName: Run JMeter from binary
    jobs:
      - job: Jmeter
        displayName: Test
        steps:
          - pwsh: | #bash or powershell - both can run on ubuntu
              function Start-CommandInsideDocker($ContainerName, $Command){
                docker exec $ContainerName sh -c "${Command}"
              }
              Write-Host "Mounting $(repoDir) to JMeter container"
              #Running Jmeter container in detached mode with volumes mounted
              docker run -d --rm `
              --name $(containerName) `
              --entrypoint tail `
              --volume $(repoDir):$(containerDir) $(containerImage) `
              -f /dev/null

              #Showing container started
              Write-Host "Started container $(containerImage) "
              docker ps -a --no-trunc --filter name=^/$(containerName)$

              #command is executed inside ubuntu-like container
              Start-CommandInsideDocker "$(containerName)" "ls $(containerDir) && mkdir -p $(containerDir)/html"
              Start-CommandInsideDocker "$(containerName)" "sh /jmeter/apache-jmeter-*/bin/jmeter.sh -n -t $(containerDir)/${{ parameters.JMXFile}} ${{ parameters.JMeterParameters}} -e -o $(containerDir)/html -l $(containerDir)/jmeter.log"

              #stop container
              docker stop "$(containerName)"
            displayName: Run Test

          - task: PublishPipelineArtifact@1
            displayName: Archive JMeter Artifacts
            inputs:
              path: $(repoDir)/jmeter.log
              artifact: JmeterFiles

          - task: PublishPipelineArtifact@1
            displayName: Archive JMeter HTML Report
            inputs:
              path: $(repoDir)/html
              artifact: JmeterReport